---
title: "LDOPA Correlation"
author: "Evan Udine"
date: "`r Sys.Date()`"
output:
 rmarkdown::html_document:
   theme: spacelab
   highlight: zenburn
   code_folding: show
   toc: true
   toc_float: true
   smooth_scroll: true
   self_contained: true 
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
```

```{r load_data}
x = read.csv('Desktop/Sinai/ASHG/ldopa_nyu_test.csv', header = T)
dim(x)
#x = x[x$ldopa > 0,]
x$samples = gsub('-.*', '', x$samples)
dim(x)
exp = read.table('Desktop/MyND/Paper_Dec_2019/differential_expression_11.04.2019/mynd_voom_residuals.txt', header = T, check.names = F)
#head(exp)
genes = read.table('Desktop/MyND/Paper_Dec_2019/differential_expression_11.04.2019/dge/rsem.mynd.design_1.txt', hea =T)
#head(exp)
pheno = read.table('Desktop/MyND/Paper_Dec_2019/differential_expression_11.04.2019/mynd_metadata_9_19_19.txt', header = T)



colnames(exp) = gsub('-.*', '', colnames(exp))
colnames(exp) = gsub('_.*', '', colnames(exp))
#head(exp)
rownames(x) = x$samples
#head(x)


texp = data.frame(t(exp), check.names = F)
tot = merge(texp, x, by = 0)
#head(tot)
dim(tot)
tot$Row.names = NULL
tot$samples = NULL

tot = as.matrix(tot)
dim(tot)
```

## L Dopa Analysis
```{r analysis, echo=FALSE}
#convert data to matrix
tot = as.matrix(tot)
#Create empty vector
a <- vector("list", 13668)

#loop through matrix and run correlation across all columns of matrix
for (i in 1:13668) {
 a[[i]] = data.frame(cor.test(tot[,"ldopa"], tot[,i], method = "kendall")[c("p.value", "estimate", "statistic")])
}
head(a)
#Organize Results
lres <- sapply(a, '[', c("p.value","estimate","statistic"))
x = data.frame(t(lres))
head(x)
x$p.value = unlist(x$p.value)
x$estimate = unlist(x$estimate)
x$statistic = unlist(x$statistic)

x = x[order(x$p.value),]
#remove ldopa correlation with itself
x = x[-c(1),]

#Run fdr correction
x$fdr = p.adjust(x$p.value)

#-log10 for plotting
x$logp = -log10(x$p.value)
range(x$fdr)

#Create 'volcano plot' for association
ggplot(x, aes(estimate, logp, color = fdr)) + geom_point() + theme_bw()

```


