---
title: "RNAseq Post Analysis Visualization"
author: "Evan Udine"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document: 
   code_folding: show
   toc: true
   toc_float: true
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require("sva")) BiocManager::install("sva"); library("sva")
if(!require("limma")) install.packages("limma"); library("limma")
if(!require("stats")) install.packages("stats"); library("stats")
if(!require("ggfortify")) install.packages("ggfortify"); library("ggfortify")
if(!require("gplots")) install.packages("gplots"); library("gplots")
if(!require("factoextra")) install.packages("factoextra"); library("factoextra")
if(!require("sva")) BiocManager::install("sva"); library("sva")
if(!require("pamr")) BiocManager::install("pamr"); library("pamr")
if(!require("DESeq2")) BiocManager::install("DESeq2"); library("DESeq2")
if(!require("edgeR")) BiocManager::install("edgeR"); library("edgeR")
if(!require("broom")) BiocManager::install("broom"); library("broom")
```


```{r pca.model, echo=TRUE, fig.width=8, fig.height=10, res=300}
library(data.table)

peer = read.table('/sc/hydra/projects/pd-omics/evan/eqtl/eur_amr_eqtl_v1/eur_amr_10.PEER_covariates.txt', header = T, check.names = F, row.names = 1)
#head(peer)
metadata_all = read.table('/sc/hydra/projects/pd-omics/evan/eqtl/eur_amr_eqtl_v1/eur_amr_metadata.txt', header = T, check.names = F, stringsAsFactors=FALSE)
#head(metadata_all)
rownames(metadata_all) = metadata_all$gsa_michael_id
peer = peer[rownames(metadata_all)]

metadata_all$gender[metadata_all$gender %in% "F"] <- 1
metadata_all$gender[metadata_all$gender %in% "M"] <- 2
metadata_all$gender = as.numeric(metadata_all$gender)

metadata_all$process_location[metadata_all$process_location %in% "HIMC"] <- 1
metadata_all$process_location[metadata_all$process_location %in% "Raj_Lab"] <- 2
metadata_all$process_location = as.numeric(metadata_all$process_location)

metadata_all$status[metadata_all$status %in% "PD"] <- 1
metadata_all$status[metadata_all$status %in% "Control"] <- 2
metadata_all$status = as.numeric(metadata_all$status)

metadata_all$aj_status[metadata_all$aj_status %in% "AJ"] <- 1
metadata_all$aj_status[metadata_all$aj_status %in% "NO"] <- 0
metadata_all$aj_status = as.numeric(metadata_all$aj_status)


covariates = c( "pbmc_counts",
                "monocyte_count",
                "blood_ml",
                "status",
                "gender",
                "age",
                "library_batch",
                "lane",
                "rin_value",
                "rna_batch",
                "TOTAL_READS",
                "aj_status",
                "mds1",
                "mds2",
                "mds3",
                "mds4",
                "mds5",
                "mds6",
                "mds7",
                "mds8",
                "mds9",
                "mds10",
                "PCT_RIBOSOMAL_BASES",     
                "PCT_CODING_BASES",     
                "PCT_UTR_BASES",     
                "PCT_INTRONIC_BASES",     
                "PCT_INTERGENIC_BASES",     
                "PCT_MRNA_BASES",     
                "PCT_USABLE_BASES" )

matrix_rsquared = matrix(NA, nrow = length(covariates), ncol = 10) #Number of factors
matrix_pvalue = matrix(NA, nrow = length(covariates), ncol = 10)
peert = as.matrix(t(peer))

for (x in 1:length(covariates)){
  for (y in 1:10){
    matrix_rsquared[x,y] <- summary( lm(peert[,y] ~ metadata_all[,covariates[x]]) )$adj.r.squared
    matrix_pvalue[x,y] <- glance(summary( lm(peert[,y] ~ metadata_all[,covariates[x]]) ))$p.value #To insert pvalues in the heatmap
  }
}

rownames(matrix_rsquared) = tolower(covariates)
rownames(matrix_pvalue) = tolower(covariates) 
#matrix_pvalue = p.adjust(matrix_pvalue, method = "bonferroni")
matrix_pvalue = matrix(p.adjust(as.vector(as.matrix(matrix_pvalue)), method='bonferroni'),ncol=ncol(matrix_pvalue))
matrix_pvalue = formatC(matrix_pvalue, format = "e", digits = 2)

#png(paste0(work_plots, "LinearReg_sva_network_bonf_230s_pvalues.png"), width = 8, height = 10, res = 300, units = "in")
heatmap.2(as.matrix(matrix_rsquared), col = colorRampPalette(RColorBrewer::brewer.pal(6,"RdPu"))(40),
          scale="none",
#          cellnote = matrix_pvalue,
#          notecol="black",
#          notecex = 0.6,
          margins=c(10,12), # ("margin.Y", "margin.X")
          trace='none', 
          dendrogram=c("row"),
          density.info='none', 
          denscol="black",
          breaks = seq(0, 1, length.out = 41),
          Colv = FALSE,
          xlab = "Factors",
          ylab = "Covariates",
          key = TRUE,
          keysize = 1,
          key.title = "teste",
          key.xlab = "Adjusted R2",
          key.ylab = NULL,
          key.xtickfun = NULL,
          key.ytickfun = NULL,
          key.par=list()
          #          main = "Linear regression between sva_network and covariates"
) 
```
